### ISSUE TITLE
How to using for Android

### ISSUE THREAD

**Issue by pvtai** [liuzy88/aspose-words-crack#1]
I have download "aspose-words-20.12-jdk17-cracked.jar" and "javassist-3.24.1-GA.jar" but I can't run it
It always crash:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aspose/words/internal/zzYVE;
        at com.aspose.words.internal.zz3E.zzZ(Unknown Source:243)
        at com.aspose.words.internal.zz3F.zzN(Unknown Source:1456)
        at com.aspose.words.internal.zz3F.zzO(Unknown Source:404)
        at com.aspose.words.internal.zz2Q.<init>(Unknown Source:36)
        at com.aspose.words.internal.zz2Q.<init>(Unknown Source:529)
        at com.aspose.words.internal.zz2Q.zzL(Unknown Source:480)
        at com.aspose.words.internal.zz2Q.zzoQ(Unknown Source:504)
        at com.aspose.words.internal.zz2Q.<clinit>(Unknown Source:516)
        at com.aspose.words.internal.zz18.zznl(Unknown Source:164)
        at com.aspose.words.internal.zz18.zzu9(Unknown Source:46)
        at com.aspose.words.internal.zzZWQ.zzj2(Unknown Source:43)
        at com.aspose.words.internal.zzZYQ.zzU(Unknown Source:93)
        at com.aspose.words.internal.zz83.zzo(Unknown Source:514)
        at com.aspose.words.zzZUQ.zzZkD(Unknown Source:242)
        at com.aspose.words.zzZUQ.zzY(Unknown Source:62)
        at com.aspose.words.Document.zzY(Unknown Source:1724)
        at com.aspose.words.Document.zzZ(Unknown Source:1691)
        at com.aspose.words.Document.<init>(Unknown Source:188)
        at com.aspose.words.Document.<init>(Unknown Source:154)
```

Thank you

**Comment by ai1361720220000** [comment]
我遇到同样的问题，请问解决了吗

> I have download "aspose-words-20.12-jdk17-cracked.jar" and "javassist-3.24.1-GA.jar" but I can't run it
> It always crash:
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aspose/words/internal/zzYVE;
>         at com.aspose.words.internal.zz3E.zzZ(Unknown Source:243)
>         at com.aspose.words.internal.zz3F.zzN(Unknown Source:1456)
>         at com.aspose.words.internal.zz3F.zzO(Unknown Source:404)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:36)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:529)
>         at com.aspose.words.internal.zz2Q.zzL(Unknown Source:480)
>         at com.aspose.words.internal.zz2Q.zzoQ(Unknown Source:504)
>         at com.aspose.words.internal.zz2Q.<clinit>(Unknown Source:516)
>         at com.aspose.words.internal.zz18.zznl(Unknown Source:164)
>         at com.aspose.words.internal.zz18.zzu9(Unknown Source:46)
>         at com.aspose.words.internal.zzZWQ.zzj2(Unknown Source:43)
>         at com.aspose.words.internal.zzZYQ.zzU(Unknown Source:93)
>         at com.aspose.words.internal.zz83.zzo(Unknown Source:514)
>         at com.aspose.words.zzZUQ.zzZkD(Unknown Source:242)
>         at com.aspose.words.zzZUQ.zzY(Unknown Source:62)
>         at com.aspose.words.Document.zzY(Unknown Source:1724)
>         at com.aspose.words.Document.zzZ(Unknown Source:1691)
>         at com.aspose.words.Document.<init>(Unknown Source:188)
>         at com.aspose.words.Document.<init>(Unknown Source:154)
> ```
> 
> Thank you

我遇到同样的问题，请问解决了吗

**Comment by ai1361720220000** [comment]
> I have download "aspose-words-20.12-jdk17-cracked.jar" and "javassist-3.24.1-GA.jar" but I can't run it
> It always crash:
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aspose/words/internal/zzYVE;
>         at com.aspose.words.internal.zz3E.zzZ(Unknown Source:243)
>         at com.aspose.words.internal.zz3F.zzN(Unknown Source:1456)
>         at com.aspose.words.internal.zz3F.zzO(Unknown Source:404)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:36)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:529)
>         at com.aspose.words.internal.zz2Q.zzL(Unknown Source:480)
>         at com.aspose.words.internal.zz2Q.zzoQ(Unknown Source:504)
>         at com.aspose.words.internal.zz2Q.<clinit>(Unknown Source:516)
>         at com.aspose.words.internal.zz18.zznl(Unknown Source:164)
>         at com.aspose.words.internal.zz18.zzu9(Unknown Source:46)
>         at com.aspose.words.internal.zzZWQ.zzj2(Unknown Source:43)
>         at com.aspose.words.internal.zzZYQ.zzU(Unknown Source:93)
>         at com.aspose.words.internal.zz83.zzo(Unknown Source:514)
>         at com.aspose.words.zzZUQ.zzZkD(Unknown Source:242)
>         at com.aspose.words.zzZUQ.zzY(Unknown Source:62)
>         at com.aspose.words.Document.zzY(Unknown Source:1724)
>         at com.aspose.words.Document.zzZ(Unknown Source:1691)
>         at com.aspose.words.Document.<init>(Unknown Source:188)
>         at com.aspose.words.Document.<init>(Unknown Source:154)
> ```
> 
> Thank you

hello, i met the same error when using for android. Have you solved the problem?

**Comment by DevTrinh** [comment]
> I have download "aspose-words-20.12-jdk17-cracked.jar" and "javassist-3.24.1-GA.jar" but I can't run it It always crash:
> 
> ```
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aspose/words/internal/zzYVE;
>         at com.aspose.words.internal.zz3E.zzZ(Unknown Source:243)
>         at com.aspose.words.internal.zz3F.zzN(Unknown Source:1456)
>         at com.aspose.words.internal.zz3F.zzO(Unknown Source:404)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:36)
>         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:529)
>         at com.aspose.words.internal.zz2Q.zzL(Unknown Source:480)
>         at com.aspose.words.internal.zz2Q.zzoQ(Unknown Source:504)
>         at com.aspose.words.internal.zz2Q.<clinit>(Unknown Source:516)
>         at com.aspose.words.internal.zz18.zznl(Unknown Source:164)
>         at com.aspose.words.internal.zz18.zzu9(Unknown Source:46)
>         at com.aspose.words.internal.zzZWQ.zzj2(Unknown Source:43)
>         at com.aspose.words.internal.zzZYQ.zzU(Unknown Source:93)
>         at com.aspose.words.internal.zz83.zzo(Unknown Source:514)
>         at com.aspose.words.zzZUQ.zzZkD(Unknown Source:242)
>         at com.aspose.words.zzZUQ.zzY(Unknown Source:62)
>         at com.aspose.words.Document.zzY(Unknown Source:1724)
>         at com.aspose.words.Document.zzZ(Unknown Source:1691)
>         at com.aspose.words.Document.<init>(Unknown Source:188)
>         at com.aspose.words.Document.<init>(Unknown Source:154)
> ```
> 
> Thank you

Hello friend, have you successfully converted the word to pdf file?

**Comment by DevTrinh** [comment]
> > I have download "aspose-words-20.12-jdk17-cracked.jar" and "javassist-3.24.1-GA.jar" but I can't run it
> > It always crash:
> > ```
> > java.lang.NoClassDefFoundError: Failed resolution of: Lcom/aspose/words/internal/zzYVE;
> >         at com.aspose.words.internal.zz3E.zzZ(Unknown Source:243)
> >         at com.aspose.words.internal.zz3F.zzN(Unknown Source:1456)
> >         at com.aspose.words.internal.zz3F.zzO(Unknown Source:404)
> >         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:36)
> >         at com.aspose.words.internal.zz2Q.<init>(Unknown Source:529)
> >         at com.aspose.words.internal.zz2Q.zzL(Unknown Source:480)
> >         at com.aspose.words.internal.zz2Q.zzoQ(Unknown Source:504)
> >         at com.aspose.words.internal.zz2Q.<clinit>(Unknown Source:516)
> >         at com.aspose.words.internal.zz18.zznl(Unknown Source:164)
> >         at com.aspose.words.internal.zz18.zzu9(Unknown Source:46)
> >         at com.aspose.words.internal.zzZWQ.zzj2(Unknown Source:43)
> >         at com.aspose.words.internal.zzZYQ.zzU(Unknown Source:93)
> >         at com.aspose.words.internal.zz83.zzo(Unknown Source:514)
> >         at com.aspose.words.zzZUQ.zzZkD(Unknown Source:242)
> >         at com.aspose.words.zzZUQ.zzY(Unknown Source:62)
> >         at com.aspose.words.Document.zzY(Unknown Source:1724)
> >         at com.aspose.words.Document.zzZ(Unknown Source:1691)
> >         at com.aspose.words.Document.<init>(Unknown Source:188)
> >         at com.aspose.words.Document.<init>(Unknown Source:154)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you
> 
> hello, i met the same error when using for android. Have you solved the problem?

Hello friend, have you successfully converted the word to pdf file?
